name: Build
on:
  push:
    branches: [ "master", "1.0.x" ]
  release:
    branches: [ "master", "1.0.x" ]
  pull_request:
    branches: [ "master", "1.0.x" ]
env:
  BUILD_TYPE: RelWithDebInfo
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
        build_type: [Release, Debug]
        c_compiler: [gcc, clang]
        cpp_compiler: [g++, clang++]
    steps:
    - uses: actions/checkout@v4
    - name: Prepare
      run: sudo apt update && sudo apt install -y pkg-config doxygen libpugixml-dev libwayland-dev libegl-dev
    - name: Configure
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -S ${{ github.workspace }} -DBUILD_DOCUMENTATION=ON -DBUILD_EXAMPLES=ON -DBUILD_SHARED_LIBS=ON -DBUILD_SERVER=ON
    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}
